### ISSUE TITLE
Where is the index.html ?

### ISSUE THREAD

**Issue by lbjones** [sgraewe/nuxt-tailwind#2]
Hey great template, thanks!

This may be a newbie question, but I started with a new project then ran `npm run build`.

First question, the code is place in `.nuxt/dist`?  I don't see where that is configured.  And second, there is no `index.html`, just an `index.ssr.html` and `index.spa.html`?  Is this an error, or does it indicate a different type of build than I'm used to?

**Comment by sgraewe** [comment]
First, sry for the late response. :disappointed:

Nuxt doesn't use an index.html by default  but you can create one by yourself:
https://nuxtjs.org/guide/views#document

The code you work with is inside the `template `folder.
After you run build, the compiled code will be placed in `dist`
