### ISSUE TITLE
z-index value

### ISSUE THREAD

**Issue by smbdelse** [sgraewe/nuxt-tailwind#3]
I've run into strange issue when compiling Tailwind. All z-index-es I get has only first digit. When I'll put
'75': 75 in tailwind.config.js in zIndex obj, all that gets parsed is .z-75{z-index:7}. Can anyone confirm that behavior?

**Comment by sgraewe** [comment]
Sry for the late response.

Will test this later today.

**Comment by smbdelse** [comment]
Ok, i found that, not only Tailwind, but all css's in the project was affected. It's cssnano fault. There is an option to turn off z-index change by setting zindex: false in it's options, but unfortunately I didn't see a difference, so for now I turned it off completely.

**Comment by sgraewe** [comment]
Hm the `postcss-zindex` plugin should be deactivated by default.
I will test this later

**Comment by sgraewe** [comment]
Alright, fixed it :)

feb39a842671a04e9863953f184f0314ed5840eb
